title: HUANGMOXUAN's Homepage
page-top-title: HUANGMOXUAN
top-section-bg-text: Artificial Intelligence
home-subtitle: HUANGMOXUAN&ensp;|&ensp;黄墨轩
copyright-text: '&copy; HUANGMOXUAN 2025-2026. All Rights Reserved.'
